.decl BasicBlockBegin(v: symbol)
.input BasicBlockBegin(IO="file", filename="BasicBlockBegin.csv", delimiter="\t")

.decl BasicBlockHead(v: symbol,g:symbol)
.input BasicBlockHead(IO="file", filename="BasicBlockHead.csv", delimiter="\t")

.decl OutOpt(?s:symbol, ?x:symbol)
.decl couBB(n:number)
OutOpt(?x,?head):- BasicBlockBegin(?head), BasicBlockHead(?x,?head).

couBB(count:{OutOpt(_,_)}).
couBB(count:{BasicBlockHead(_,_)}).

.output couBB